import pandas as pd
import numpy as np
from tool import generate_dataset

def reference_cleaning(df):
    """Ground-truth reference cleaning function."""
    df = df[df["age"].notna() & (df["age"] <= 100)].copy()
    for col in ["height", "weight"]:
        df[col].fillna(df[col].mean(), inplace=True)
    df = (df - df.mean()) / df.std()
    return df

def grade(model_fn):
    """
    Grade the LLM's cleaning function.

    Parameters:
        model_fn: callable
            Function generated by the LLM that takes a DataFrame and returns a cleaned one.

    Returns:
        score: float (0.0–1.0)
        message: str
    """
    df = generate_dataset()
    expected = reference_cleaning(df.copy())

    try:
        output_df = model_fn(df.copy())
    except Exception as e:
        return 0.0, f"Error during execution: {e}"

    # 1️⃣ Check columns
    if not all(col in output_df.columns for col in expected.columns):
        return 0.0, "Missing columns."

    # 2️⃣ Check filtering
    if len(output_df) != len(expected):
        return 0.3, "Incorrect filtering of age or NaN values."

    # 3️⃣ Check missing values
    if output_df.isna().sum().any():
        return 0.4, "Missing values not imputed."

    # 4️⃣ Check standardization
    mean_close = np.allclose(output_df.mean(), 0, atol=0.1)
    std_close = np.allclose(output_df.std(), 1, atol=0.1)
    if mean_close and std_close:
        return 1.0, "Pass."
    else:
        return 0.7, "Standardization incorrect."
